"""Internal data tables for LaTeX ↔ Unicode ↔ HTML conversion.

Not part of the public API — imported only by _latex.py.
"""

from html.entities import name2codepoint

_HTML_ENTITY_TO_LATEX = {
    "amp": "&",
    "apos": "'",
    "quot": '"',
    "lt": "<",
    "gt": ">",
    "nbsp": "{~}",
    "copy": r"{\copyright}",
    "reg": r"{\textregistered}",
    "trade": r"{\texttrademark}",
    "pound": r"{\pounds}",
    "euro": r"{\euro}",
    "sect": r"{{\S}}",
    "para": r"{{\P}}",
    "laquo": r"{\guillemotleft}",
    "raquo": r"{\guillemotright}",
    "ndash": "--",
    "mdash": "---",
    "hellip": r"\ldots",
    "times": r"$\times$",
    "divide": r"$\div$",
    "plusmn": r"$\pm$",
    "deg": r"{$^{\circ}$}",
    "micro": r"$\mu$",
    "mu": r"$\mu$",
    "aring": r"{{\aa}}",
    "Aring": r"{{\AA}}",
    "aelig": r"{\ae}",
    "AElig": r"{{\AE}}",
    "oslash": r"{\o}",
    "Oslash": r"{{\O}}",
    "szlig": r"{\ss}",
    "thorn": r"{\th}",
    "THORN": r"{{\TH}}",
    "eth": r"{\dh}",
    "ETH": r"{{\DH}}",
    "alpha": r"$\alpha$",
    "beta": r"$\beta$",
    "gamma": r"$\gamma$",
    "delta": r"$\delta$",
    "epsilon": r"$\epsilon$",
    "Epsilon": r"{{$\Epsilon$}}",
    "Gamma": r"{{$\Gamma$}}",
    "Delta": r"{{$\Delta$}}",
    "Theta": r"{{$\Theta$}}",
    "Lambda": r"{{$\Lambda$}}",
    "Xi": r"{{$\Xi$}}",
    "Pi": r"{{$\Pi$}}",
    "Sigma": r"{{$\Sigma$}}",
    "Upsilon": r"{{$\Upsilon$}}",
    "Phi": r"{{$\Phi$}}",
    "Psi": r"{{$\Psi$}}",
    "Omega": r"{{$\Omega$}}",
}
_HTML_NUMERIC_TO_LATEX: dict[int, str] = {
    160: r"{~}",
    169: r"{\copyright}",
    174: r"{\textregistered}",
    177: r"$\pm$",
    181: r"$\mu$",
    215: r"$\times$",
    247: r"$\div$",
    8211: "--",
    8212: "---",
    8230: r"\ldots",
}
_HTML_ACCENT_CODES = {
    768: "`",
    769: "'",
    770: "^",
    771: "~",
    772: "=",
    774: "u",
    775: ".",
    776: '"',
    778: "r",
    780: "v",
    803: "d",
    807: "c",
    808: "k",
}

# JabRef maps each of these Latin characters to this spelling, rather than
# through a generic Unicode encoder (which deliberately has fewer braces).
for _letter, _latex in {
    "à": r"{\`{a}}",
    "á": r"{\'{a}}",
    "â": r"{\^{a}}",
    "ã": r"{\~{a}}",
    "ä": r"{\"{a}}",
    "å": r"{{\aa}}",
    "ç": r"{\c{c}}",
    "è": r"{\`{e}}",
    "é": r"{\'{e}}",
    "ê": r"{\^{e}}",
    "ë": r"{\"{e}}",
    "ì": r"{\`{i}}",
    "í": r"{\'{i}}",
    "î": r"{\^{i}}",
    "ï": r"{\"{i}}",
    "ñ": r"{\~{n}}",
    "ò": r"{\`{o}}",
    "ó": r"{\'{o}}",
    "ô": r"{\^{o}}",
    "õ": r"{\~{o}}",
    "ö": r"{\"{o}}",
    "ù": r"{\`{u}}",
    "ú": r"{\'{u}}",
    "û": r"{\^{u}}",
    "ü": r"{\"{u}}",
    "ý": r"{\'{y}}",
    "ÿ": r"{\"{y}}",
    "À": r"{{\`{A}}}",
    "Á": r"{{\'{A}}}",
    "Â": r"{{\^{A}}}",
    "Ã": r"{{\~{A}}}",
    "Ä": r"{{\"{A}}}",
    "Å": r"{{\AA}}",
    "Ç": r"{{\c{C}}}",
    "È": r"{{\`{E}}}",
    "É": r"{{\'{E}}}",
    "Ê": r"{{\^{E}}}",
    "Ë": r"{{\"{E}}}",
    "Ì": r"{{\`{I}}}",
    "Í": r"{{\'{I}}}",
    "Î": r"{{\^{I}}}",
    "Ï": r"{{\"{I}}}",
    "Ñ": r"{{\~{N}}}",
    "Ò": r"{{\`{O}}}",
    "Ó": r"{{\'{O}}}",
    "Ô": r"{{\^{O}}}",
    "Õ": r"{{\~{O}}}",
    "Ö": r"{{\"{O}}}",
    "Ù": r"{{\`{U}}}",
    "Ú": r"{{\'{U}}}",
    "Û": r"{{\^{U}}}",
    "Ü": r"{{\"{U}}}",
    "Ý": r"{{\'{Y}}}",
}.items():
    _HTML_NUMERIC_TO_LATEX[ord(_letter)] = _latex

for _name, _latex in _HTML_ENTITY_TO_LATEX.items():
    if _name in name2codepoint:
        _HTML_NUMERIC_TO_LATEX.setdefault(name2codepoint[_name], _latex)
for _name, _codepoint in name2codepoint.items():
    if _codepoint in _HTML_NUMERIC_TO_LATEX:
        _HTML_ENTITY_TO_LATEX.setdefault(_name, _HTML_NUMERIC_TO_LATEX[_codepoint])
