/**
 * Vendor the pynakes engine into `editor/engine/` for shipping inside the VSIX.
 *
 * The extension bundles the engine so a user needs only a Python interpreter,
 * not a pynakes install. Every runtime dependency of pynakes is a pure-Python
 * `py3-none-any` wheel, so one universal bundle works on every platform and
 * there is no per-platform build matrix and nothing to code-sign.
 *
 * Two details here are load-bearing, both measured rather than assumed:
 *
 *   - The tree is left UNZIPPED. A compressed zipapp is a tenth of the size but
 *     pays zip decompression on every import, which measured ~4x slower per
 *     invocation (0.68s vs 0.17s). Size is cheap in a VSIX; latency is not.
 *   - The `.dist-info` directories are KEPT. `pynakes.__version__` comes from
 *     `importlib.metadata.version("pynakes")`, so without them the bundled
 *     engine reports whatever other pynakes is on `sys.path` — the user's
 *     ambient install — or `0.0.0+unknown`. Engine selection compares that
 *     version, so a bundle that misreports itself would pick the wrong engine.
 *
 * Usage: `npm run vendor-engine` (set PYNAKES_VENDOR_PYTHON to choose a
 * different interpreter for the build).
 */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const extensionRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(extensionRoot, "..");
const engineDir = path.join(extensionRoot, "engine");

/** Console scripts carry absolute shebangs from the build machine. */
const USELESS_ENTRIES = ["bin", "Scripts"];

function run(command, args, options = {}) {
  return execFileSync(command, args, { encoding: "utf8", stdio: "pipe", ...options });
}

/** The interpreter used to build the bundle; not the one that will run it. */
function buildPython() {
  const candidates = [process.env.PYNAKES_VENDOR_PYTHON, "python3", "python"].filter(Boolean);
  for (const candidate of candidates) {
    try {
      run(candidate, ["-c", "import sys; assert sys.version_info >= (3, 12)"]);
      return candidate;
    } catch {
      continue;
    }
  }
  throw new Error(
    "No Python 3.12+ found to build the bundle. Set PYNAKES_VENDOR_PYTHON to an interpreter.",
  );
}

function removeRecursive(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

/** Drop caches and build-machine-specific entries from the vendored tree. */
function prune(root) {
  for (const name of USELESS_ENTRIES) {
    removeRecursive(path.join(root, name));
  }
  for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
    if (entry.isDirectory() && entry.name === "__pycache__") {
      removeRecursive(path.join(entry.parentPath ?? entry.path, entry.name));
    }
  }
}

/** Read the vendored engine's own version from the metadata it ships with. */
function vendoredVersion(root) {
  const distInfo = fs
    .readdirSync(root)
    .find((name) => name.startsWith("pynakes-") && name.endsWith(".dist-info"));
  if (!distInfo) {
    throw new Error("Vendored tree has no pynakes .dist-info; the bundle would misreport itself.");
  }
  const metadata = fs.readFileSync(path.join(root, distInfo, "METADATA"), "utf8");
  const version = /^Version:\s*(.+)$/m.exec(metadata)?.[1]?.trim();
  if (!version) {
    throw new Error(`No Version field in ${distInfo}/METADATA.`);
  }
  return version;
}

function directorySize(root) {
  let total = 0;
  for (const entry of fs.readdirSync(root, { withFileTypes: true, recursive: true })) {
    if (entry.isFile()) {
      total += fs.statSync(path.join(entry.parentPath ?? entry.path, entry.name)).size;
    }
  }
  return total;
}

/** The launcher: a stable entry point that puts the bundle on `sys.path` itself. */
const LAUNCHER_NAME = "pynakes_launcher.py";

/**
 * Write the launcher the extension invokes.
 *
 * Invoking a script rather than `-m pynakes` means the extension needs no
 * `PYTHONPATH` and no environment mutation: Python puts the script's own
 * directory on `sys.path`, and the explicit insert makes that independent of
 * how the interpreter was started.
 *
 * The interpreter guard is what lets discovery reject an interpreter that is
 * too old without probing for its version separately — a Python below the
 * floor exits non-zero and prints no version, which is exactly the signal an
 * unusable candidate produces anyway.
 */
function writeLauncher(root, minimumPython) {
  const [major, minor] = minimumPython.split(".");
  const source = `"""Entry point for the copy of pynakes bundled with the VS Code extension.

Generated by editor/scripts/vendor-engine.mjs. Do not edit by hand.
"""

import os
import sys

if sys.version_info < (${major}, ${minor}):
    sys.stderr.write(
        "pynakes needs Python ${minimumPython} or newer, but this interpreter is "
        + ".".join(str(part) for part in sys.version_info[:3])
        + ".\\n"
    )
    raise SystemExit(1)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pynakes.cli import app

app()
`;
  fs.writeFileSync(path.join(root, LAUNCHER_NAME), source, "utf8");
}

/**
 * Confirm the bundle runs and identifies itself as the version it ships.
 *
 * This is the check that would catch a stripped `.dist-info`: it runs from a
 * scratch directory so that if the bundle resolved some other pynakes, the
 * reported version would disagree with its own metadata. `-P` keeps the
 * working directory off `sys.path` — defensive rather than load-bearing, since
 * script invocation already uses the script's directory instead of the cwd.
 */
function smokeTest(python, root, expectedVersion) {
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), "pynakes-vendor-"));
  try {
    const reported = run(python, ["-P", path.join(root, LAUNCHER_NAME), "--version"], {
      cwd: scratch,
    }).trim();
    if (reported !== expectedVersion) {
      throw new Error(
        `Bundled engine reports ${reported} but its metadata says ${expectedVersion}. ` +
          "The bundle is resolving a different pynakes than the one it ships.",
      );
    }
    return reported;
  } finally {
    removeRecursive(scratch);
  }
}

const python = buildPython();
console.log(`Building the engine bundle with ${python}`);

removeRecursive(engineDir);
const wheelDir = fs.mkdtempSync(path.join(os.tmpdir(), "pynakes-wheel-"));
try {
  run(python, ["-m", "pip", "wheel", repoRoot, "--no-deps", "-w", wheelDir, "-q"]);
  const wheel = fs.readdirSync(wheelDir).find((name) => name.endsWith(".whl"));
  if (!wheel) {
    throw new Error(`No wheel produced from ${repoRoot}.`);
  }
  run(python, [
    "-m",
    "pip",
    "install",
    "--target",
    engineDir,
    path.join(wheelDir, wheel),
    "--no-compile",
    "--upgrade",
    "-q",
  ]);
} finally {
  removeRecursive(wheelDir);
}

prune(engineDir);
const version = vendoredVersion(engineDir);
const requiresPython = "3.12";
writeLauncher(engineDir, requiresPython);
const reported = smokeTest(python, engineDir, version);

// No timestamp: the manifest stays byte-identical for identical inputs.
fs.writeFileSync(
  path.join(engineDir, "engine.json"),
  `${JSON.stringify({ name: "pynakes", version, requiresPython, launcher: LAUNCHER_NAME }, null, 2)}\n`,
  "utf8",
);

const megabytes = (directorySize(engineDir) / 1024 / 1024).toFixed(1);
console.log(`Vendored pynakes ${reported} into engine/ (${megabytes} MB, unzipped)`);
