"""Preferred field order per entry type, for the canonical formatter."""

# Pynakes' preferred field ordering per entry type. BibTeX and BibLaTeX do not
# assign semantic meaning to field order; this is a deterministic readability
# convention, not an external standard. It keeps inheritance links first (see
# ``_STRUCTURAL_FIELDS``), then identifies the work and its publication context,
# then places identifiers/access fields and annotations toward the end. Fields
# absent from the table retain their original relative order after known fields.
_FIELD_ORDER: dict[str, list[str]] = {
    "article": [
        "author",
        "title",
        "journal",
        "year",
        "volume",
        "number",
        "pages",
        "numpages",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "book": [
        "author",
        "editor",
        "title",
        "publisher",
        "year",
        "volume",
        "series",
        "address",
        "edition",
        "month",
        "doi",
        "url",
        "note",
        "isbn",
        "abstract",
    ],
    "inproceedings": [
        "author",
        "title",
        "booktitle",
        "year",
        "editor",
        "pages",
        "volume",
        "series",
        "address",
        "publisher",
        "organization",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "incollection": [
        "author",
        "title",
        "booktitle",
        "year",
        "editor",
        "pages",
        "volume",
        "series",
        "address",
        "publisher",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "phdthesis": [
        "author",
        "title",
        "school",
        "year",
        "address",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "mastersthesis": [
        "author",
        "title",
        "school",
        "year",
        "address",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "techreport": [
        "author",
        "title",
        "institution",
        "year",
        "type",
        "number",
        "address",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "misc": [
        "author",
        "title",
        "year",
        "howpublished",
        "month",
        "url",
        "note",
        "abstract",
    ],
    "proceedings": [
        "editor",
        "title",
        "year",
        "volume",
        "series",
        "address",
        "publisher",
        "organization",
        "month",
        "doi",
        "url",
        "note",
        "abstract",
    ],
    "unpublished": [
        "author",
        "title",
        "year",
        "month",
        "note",
        "url",
        "abstract",
    ],
}
